### ISSUE TITLE
/dev/EtherCAT0 can't start without permission

### ISSUE THREAD

**Issue by enriLoniterp** [ICube-Robotics/ethercat_driver_ros2#11]
Hi @mcbed,

When you try to activate your master you may encounter few problems:

1. You haven't started your master and ros2-control might say `No such file or directory ``/dev/EtherCAT0`
2. If you started with `/etc/init.d/ethercat start` it might say `Permision denied`

If you use `/etc/init.d/ethercat start` and then `sudo chmod /dev/EtherCAT0 ` (don't know exactly minimum permission required)
This way should work.

Enrico

**Comment by mcbed** [comment]
Normally you don't need to do it. Is your `$USER` member of `ecusers` ? You can run  `$ groups` in a shell to check it.

**Comment by enriLoniterp** [comment]
yes, it is but it doesn't allow me to connect!

My current user is in the ecusers group

**Comment by ros2torial** [comment]
you can also use **sudo -s** or **sudo su** before running the commands to give all the permissions and hardware access.
