### ISSUE TITLE
how to send "reset_fault" ? 

### ISSUE THREAD

**Issue by wei1224hf** [ICube-Robotics/ethercat_driver_ros2#122]
I noticed that there is a interface called "reset_fault" , 
but I don't know how to use it, 
how to send it in console?

**Comment by wei1224hf** [comment]
I can't reset fault using this package with ros2, 
but by ethercat-igh console: ethercat download -p 0 -t uint16 0x6040 0 128

**Comment by yguel** [comment]
Hi wei1224hf,
Can you provide more information ? I guess you are working with a motor drive. Can you tell the type, the config you used, etc ?
