### ISSUE TITLE
Developing a generic driver 

### ISSUE THREAD

**Issue by alex290701** [ICube-Robotics/ethercat_driver_ros2#13]
Hello team, I am working on Omron etherCAT [coupler](https://www.ia.omron.com/products/family/3184/specification.html) and [digital I/O](https://www.ia.omron.com/products/family/3185/download/catalog.html) modules(NX-Series) with ROS2. I have all the required hardware details in an XML file. I am trying to find a generic driver which would use this XML file and connect to the corresponding etherCAT coupler and the modules. So, it would be a great help if you could suggest some repository or code to refer for developing such a driver. Thank you.

**Comment by mcbed** [comment]
Hi, from what I know there is no such driver for ROS2 yet and for sure not for ros2_control.
