### ISSUE TITLE
issue in creating generic omron IO plugin

### ISSUE THREAD

**Issue by ros2torial** [ICube-Robotics/ethercat_driver_ros2#16]
Hi,

I followed your instruction and successfully tested **beckhoff ek1100(coupler) + el1008(input module) + el2008(output module)** setup.
When running ```ethercat slaves``` command, this is the output we get..
![Screenshot from 2022-10-27 20-34-31](https://user-images.githubusercontent.com/65568235/198328413-d4c2ece0-4803-4f74-8708-2d992131e705.png)

For a project we have to use **omron nxecc202(coupler) + nxid5442(input module) + nxod5256(output module)** setup.
When I run ```ethercat slaves``` command, this is the output..
![Screenshot from 2022-10-27 20-35-12](https://user-images.githubusercontent.com/65568235/198330122-49afcfec-5f16-4ca6-9eb4-3b87424a40c4.png)

In omron setup, we don't see the input and output module listed like beckhoff setup. In case of beckhoff, the input and output module acts as a separate slave device but in case of omron, the input and output modules doesn't directly acts as slave device and couplers PDO's is connected with input and output modules.

Because of it, the procedure which you have used to create beckhoff plugins can't be used in case of omron. I guess I may have to write specific plugin for omron nxecc202+nxid5442+nxod5256 setup. Is there any way to avoid writing this specific plugin and write a generic plugins like beckhoff plugins?

**Comment by mcbed** [comment]
Hi, great news !! Please do not hesitate to create a PR to share your Omron devs !
