### ISSUE TITLE
Example for 6 Dof robot arm

### ISSUE THREAD

**Issue by william-nknguyen** [ICube-Robotics/ethercat_driver_ros2#19]
Hi, it will be great to have some example configurations to use this package with 6 DoF robot arms. Or can you provide me some links so that I can look at the implementation of this? Thank you

**Comment by Tahaaraoud97** [comment]
Hi, 
yes, it would be very helpful to provide an implementation example or some tips on how to implement the pdos into the hardware interface to send commands and receive sensor data. 
Thank you!

**Comment by mcbed** [comment]
Hi, its a good point, we are working on it !

**Comment by kouge0510** [comment]
> Hi, its a good point, we are working on it !

hi,could you tell me where the example is?
