### ISSUE TITLE
EtherCAT master doesn't start if linux kernel upgrades

### ISSUE THREAD

**Issue by ros2torial** [ICube-Robotics/ethercat_driver_ros2#24]
If the linux kernel is upgraded to new kernel(i.e. from 5.15.0-57 to 5.15.0-58) and we run
```shell
$ sudo /etc/init.d/ethercat start
```
then we get error
```shell
Starting EtherCAT master 1.5.2  modprobe: FATAL: Module ec_master not found in directory /lib/modules/5.15.0-58-generic failed
```

**Comment by mcbed** [comment]
In this case you need to rebuild and reinstall your kernel modules as they are not present in the newly installed kernel. To do so, just redo the first configuration steps from the [installation](https://github.com/ICube-Robotics/ethercat_driver_ros2/blob/main/INSTALL.md):
```shell
$ ./configure --prefix=/usr/local/etherlab  --disable-8139too --enable-generic # Ethernet driver e1000e not supported for kernels 4.X
$ make all modules
$ sudo make modules_install install
$ sudo depmod
```

**Comment by ros2torial** [comment]
Ok. 
By the way can we do something so that the kernel update doesn't affect it.

**Comment by mcbed** [comment]
You will need to do it every time you get a new kernel. So either you prevent automatic kernel updates on your system, or i can imagine you can do a script but this looks dangerous.
