### ISSUE TITLE
control the position of a motor

### ISSUE THREAD

**Issue by Brethiltaras** [ICube-Robotics/ethercat_driver_ros2#50]
Bonjour! I want to use the joint trajectory controller to control the position of my servo motor.

Below is my ROS2 control description:

`<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <ros2_control name="mySystem" type="system">
        <hardware>
            <plugin>ethercat_driver/EthercatDriver</plugin>
            <param name="master_id">0</param>
            <param name="control_frequency">10</param>
        </hardware>

        <joint name="joint_1">
            <command_interface name="position"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
            <state_interface name="effort"/>
            <ec_module name="Maxon_EPOS3">
                <plugin>ethercat_plugins/Maxon_EPOS3</plugin>
                <param name="alias">0</param>
                <param name="position">0</param>
                <param name="mode_of_operation">8</param>
            </ec_module>
        </joint>
    </ros2_control>

</robot>
`

The motor doesn't follow the controller's command. Joint state broadcaster is working correctly. I'm not sure whether the ROS2 control description is correct. Can anyone help?  

Merci Beaucoup!!!!

**Comment by mcbed** [comment]
Hi, on first glance it looks fine event if the control frequency is rather low. Did you check if the position control loop of your drive is set up correctly and that the drive is not in fault ?

**Comment by Brethiltaras** [comment]
I found the problem. It might be because I'm not using a maxon drive. I will try to adapt the driver source code to make it work with my drive. Thanks for your time!

**Comment by wei1224hf** [comment]
how to send the position command ?
by console command or , have to write some complex code?

**Comment by yguel** [comment]
Dear wei1224hf,
Actually you may use several ways to send position command, using console or using a node that publish on a topic.
Basically, you have to 
1. choose a position controller (or write one)
2. find out which topic it uses to receive command
3. you have then 2 options :
  1. send commands to that topic from command line (mainly for prototyping)
  2. use a dedicated program to publish to the topic (like one that interfaces with a joystick, keyboard, etc.)

As it is a ROS/ros control related question, I refer you to the documentation concerning those projects. You can have a look to one of the following tutorials for instance:

- https://ros2-industrial-workshop.readthedocs.io/en/latest/_source/navigation/ROS2-Turtlebot.html (how to control a turtlebot from keyboard)
- https://articulatedrobotics.xyz/mobile-robot-13-ros2-control-real/ (link with ros2 control, it uses a special program control with keyboard)

2 last things: 
1. if you post your question to one of the forum dedicated with ros2, you should indicate the controller you will use.
2. this very issue, you posted in, was closed and your question was not really related to it, so in the future you should post your question in a new issue and if you think it is related to an other provides a link to it.

Happy coding !
