### ISSUE TITLE
'updated!' log spam

### ISSUE THREAD

**Issue by robin-zealrobotics** [ICube-Robotics/ethercat_driver_ros2#77]
When using the cia402 drive and it takes a while for the drives to get initialized, every update of the master an info log statement occurs.
https://github.com/ICube-Robotics/ethercat_driver_ros2/blob/3ccdb0dd7aa747fb0173390769876bbb4b9587ee/ethercat_driver/src/ethercat_driver.cpp#L321

With our setup of 2 drives, when they start with an external safety signal telling them to lock the brakes, they can't get into 'initialized' yet. During that time, the log gets filled with this statement at a rate of 200Hz (or whatever frequency we configured).

I'm not sure whether the fact that locked brakes can't go into initialized is a problem in itself, but I'm guessing the log spam is definitely not intended.

**Comment by mcbed** [comment]
Hi @robin-zealrobotics, 
Thanx for reporting this. In fact a buggy PR was merged and was reverted, try pulling the current main branch and it should solve your issue.
