### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by muttistefano** [ICube-Robotics/ethercat_driver_ros2#86]
i think this part in the documentation might be wrong:

command_interface | Only for tpdo. Name of the command interface to be used inside ros2_control.
-- | --
state_interface | Only for rpdo. Name of the state interface to be used inside ros2_control.

found here : https://icube-robotics.github.io/ethercat_driver_ros2/user_guide/config_generic_slave.html

thanks

**Comment by yguel** [comment]
Thank you for your report. It takes us a bit of time to fix the mistake you found (and we apologize for that) but it is done now.

**Comment by muttistefano** [comment]
Thank you 😊
